export const SunnyIco = (props) => (
    <svg
      height={`${props.height ? props.height : '50mm'}`}
      viewBox="0 0 40 40"
      width={`${props.width ? props.width : '50mm'}`}
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <g
        style={{
          fill: "#6f6f6f",
          fillOpacity: 1,
        }}
      >
        <g
          style={{
            fill: "#6f6f6f",
            fillOpacity: 1,
          }}
        >
          <path
            d="M42.021 115.547a.5.5 0 0 0-.494.506v2.472a.5.5 0 1 0 1 0v-2.472a.5.5 0 0 0-.506-.506z"
            style={{
              color: "#000",
              fontStyle: "normal",
              fontVariant: "normal",
              fontWeight: 400,
              fontStretch: "normal",
              fontSize: "medium",
              lineHeight: "normal",
              fontFamily: "sans-serif",
              fontVariantLigatures: "normal",
              fontVariantPosition: "normal",
              fontVariantCaps: "normal",
              fontVariantNumeric: "normal",
              fontVariantAlternates: "normal",
              fontFeatureSettings: "normal",
              textIndent: 0,
              textAlign: "start",
              textDecoration: "none",
              textDecorationLine: "none",
              textDecorationStyle: "solid",
              textDecorationColor: "#000",
              letterSpacing: "normal",
              wordSpacing: "normal",
              textTransform: "none",
              writingMode: "lr-tb",
              direction: "ltr",
              textOrientation: "mixed",
              dominantBaseline: "auto",
              baselineShift: "baseline",
              textAnchor: "start",
              whiteSpace: "normal",
              shapePadding: 0,
              clipRule: "nonzero",
              display: "inline",
              overflow: "visible",
              visibility: "visible",
              opacity: 1,
              isolation: "auto",
              mixBlendMode: "normal",
              colorInterpolation: "sRGB",
              colorInterpolationFilters: "linearRGB",
              solidColor: "#000",
              solidOpacity: 1,
              vectorEffect: "none",
              fill: "#6f6f6f",
              fillOpacity: 1,
              fillRule: "evenodd",
              stroke: "none",
              strokeWidth: 1,
              strokeLinecap: "round",
              strokeLinejoin: "miter",
              strokeMiterlimit: 4,
              strokeDasharray: "none",
              strokeDashoffset: 0,
              strokeOpacity: 1,
              colorRendering: "auto",
              imageRendering: "auto",
              shapeRendering: "auto",
              textRendering: "auto",
              enableBackground: "accumulate",
            }}
            transform="translate(-28.274 -112.44)"
          />
          <path
            d="M47.928 126.95a5.907 5.907 0 0 0-5.9-5.9 5.905 5.905 0 0 0-5.9 5.9c0 3.252 2.647 5.9 5.9 5.9 3.252 0 5.9-2.648 5.9-5.9z"
            style={{
              color: "#000",
              fontStyle: "normal",
              fontVariant: "normal",
              fontWeight: 400,
              fontStretch: "normal",
              fontSize: "medium",
              lineHeight: "normal",
              fontFamily: "sans-serif",
              fontVariantLigatures: "normal",
              fontVariantPosition: "normal",
              fontVariantCaps: "normal",
              fontVariantNumeric: "normal",
              fontVariantAlternates: "normal",
              fontFeatureSettings: "normal",
              textIndent: 0,
              textAlign: "start",
              textDecoration: "none",
              textDecorationLine: "none",
              textDecorationStyle: "solid",
              textDecorationColor: "#000",
              letterSpacing: "normal",
              wordSpacing: "normal",
              textTransform: "none",
              writingMode: "lr-tb",
              direction: "ltr",
              textOrientation: "mixed",
              dominantBaseline: "auto",
              baselineShift: "baseline",
              textAnchor: "start",
              whiteSpace: "normal",
              shapePadding: 0,
              clipRule: "nonzero",
              display: "inline",
              overflow: "visible",
              visibility: "visible",
              opacity: 1,
              isolation: "auto",
              mixBlendMode: "normal",
              colorInterpolation: "sRGB",
              colorInterpolationFilters: "linearRGB",
              solidColor: "#000",
              solidOpacity: 1,
              vectorEffect: "none",
              fill: "#6f6f6f",
              fillOpacity: 1,
              fillRule: "nonzero",
              stroke: "none",
              strokeWidth: 1,
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeMiterlimit: 4,
              strokeDasharray: "none",
              strokeDashoffset: 15,
              strokeOpacity: 1,
              colorRendering: "auto",
              imageRendering: "auto",
              shapeRendering: "auto",
              textRendering: "auto",
              enableBackground: "accumulate",
            }}
            transform="translate(-28.274 -112.44)"
          />
          <path
            d="M31.13 126.45a.5.5 0 1 0 0 1h2.474a.5.5 0 1 0 0-1zM50.453 126.45a.5.5 0 1 0 0 1h2.47a.5.5 0 1 0 0-1zM36.06 132.402a.5.5 0 0 0-.343.15l-1.748 1.749a.5.5 0 1 0 .709.707l1.746-1.748a.5.5 0 0 0-.363-.858zM49.723 118.74a.5.5 0 0 0-.344.15l-1.748 1.749a.5.5 0 1 0 .709.707l1.746-1.748a.5.5 0 0 0-.363-.858zM34.318 118.74a.5.5 0 0 0-.35.858l1.749 1.748a.5.5 0 1 0 .707-.707l-1.746-1.748a.5.5 0 0 0-.36-.15z"
            style={{
              color: "#000",
              fontStyle: "normal",
              fontVariant: "normal",
              fontWeight: 400,
              fontStretch: "normal",
              fontSize: "medium",
              lineHeight: "normal",
              fontFamily: "sans-serif",
              fontVariantLigatures: "normal",
              fontVariantPosition: "normal",
              fontVariantCaps: "normal",
              fontVariantNumeric: "normal",
              fontVariantAlternates: "normal",
              fontFeatureSettings: "normal",
              textIndent: 0,
              textAlign: "start",
              textDecoration: "none",
              textDecorationLine: "none",
              textDecorationStyle: "solid",
              textDecorationColor: "#000",
              letterSpacing: "normal",
              wordSpacing: "normal",
              textTransform: "none",
              writingMode: "lr-tb",
              direction: "ltr",
              textOrientation: "mixed",
              dominantBaseline: "auto",
              baselineShift: "baseline",
              textAnchor: "start",
              whiteSpace: "normal",
              shapePadding: 0,
              clipRule: "nonzero",
              display: "inline",
              overflow: "visible",
              visibility: "visible",
              opacity: 1,
              isolation: "auto",
              mixBlendMode: "normal",
              colorInterpolation: "sRGB",
              colorInterpolationFilters: "linearRGB",
              solidColor: "#000",
              solidOpacity: 1,
              vectorEffect: "none",
              fill: "#6f6f6f",
              fillOpacity: 1,
              fillRule: "evenodd",
              stroke: "none",
              strokeWidth: 1,
              strokeLinecap: "round",
              strokeLinejoin: "miter",
              strokeMiterlimit: 4,
              strokeDasharray: "none",
              strokeDashoffset: 0,
              strokeOpacity: 1,
              colorRendering: "auto",
              imageRendering: "auto",
              shapeRendering: "auto",
              textRendering: "auto",
              enableBackground: "accumulate",
            }}
            transform="translate(-28.274 -112.44)"
          />
        </g>
        <path
          d="M155.91 79.008c-3.349.002-6.177 2.268-7.102 5.426-1.037-.877-2.297-1.455-3.67-1.457-3.031 0-5.457 2.366-5.701 5.336-3.301.122-5.95 2.794-5.95 6.125 0 3.409 2.761 6.17 6.17 6.17h22.678c3.41 0 6.17-2.761 6.17-6.17 0-3.148-2.381-5.658-5.426-6.038.167-.622.32-1.252.323-1.898V86.5c0-4.132-3.36-7.492-7.493-7.492z"
          style={{
            color: "#000",
            fontStyle: "normal",
            fontVariant: "normal",
            fontWeight: 400,
            fontStretch: "normal",
            fontSize: "medium",
            lineHeight: "normal",
            fontFamily: "sans-serif",
            fontVariantLigatures: "normal",
            fontVariantPosition: "normal",
            fontVariantCaps: "normal",
            fontVariantNumeric: "normal",
            fontVariantAlternates: "normal",
            fontFeatureSettings: "normal",
            textIndent: 0,
            textAlign: "start",
            textDecoration: "none",
            textDecorationLine: "none",
            textDecorationStyle: "solid",
            textDecorationColor: "#000",
            letterSpacing: "normal",
            wordSpacing: "normal",
            textTransform: "none",
            writingMode: "lr-tb",
            direction: "ltr",
            textOrientation: "mixed",
            dominantBaseline: "auto",
            baselineShift: "baseline",
            textAnchor: "start",
            whiteSpace: "normal",
            shapePadding: 0,
            clipRule: "nonzero",
            display: "inline",
            overflow: "visible",
            visibility: "visible",
            opacity: 1,
            isolation: "auto",
            mixBlendMode: "normal",
            colorInterpolation: "sRGB",
            colorInterpolationFilters: "linearRGB",
            solidColor: "#000",
            solidOpacity: 1,
            vectorEffect: "none",
            fill: "#6f6f6f",
            fillOpacity: 1,
            fillRule: "nonzero",
            stroke: "none",
            strokeWidth: 1,
            strokeLinecap: "round",
            strokeLinejoin: "round",
            strokeMiterlimit: 4,
            strokeDasharray: "none",
            strokeDashoffset: 15,
            strokeOpacity: 1,
            colorRendering: "auto",
            imageRendering: "auto",
            shapeRendering: "auto",
            textRendering: "auto",
            enableBackground: "accumulate",
          }}
          transform="translate(-129.796 -63.715)"
        />
      </g>
      <path
        d="M42.021 115.547a.5.5 0 0 0-.494.506v2.472a.5.5 0 1 0 1 0v-2.472a.5.5 0 0 0-.506-.506z"
        style={{
          color: "#000",
          fontStyle: "normal",
          fontVariant: "normal",
          fontWeight: 400,
          fontStretch: "normal",
          fontSize: "medium",
          lineHeight: "normal",
          fontFamily: "sans-serif",
          fontVariantLigatures: "normal",
          fontVariantPosition: "normal",
          fontVariantCaps: "normal",
          fontVariantNumeric: "normal",
          fontVariantAlternates: "normal",
          fontFeatureSettings: "normal",
          textIndent: 0,
          textAlign: "start",
          textDecoration: "none",
          textDecorationLine: "none",
          textDecorationStyle: "solid",
          textDecorationColor: "#000",
          letterSpacing: "normal",
          wordSpacing: "normal",
          textTransform: "none",
          writingMode: "lr-tb",
          direction: "ltr",
          textOrientation: "mixed",
          dominantBaseline: "auto",
          baselineShift: "baseline",
          textAnchor: "start",
          whiteSpace: "normal",
          shapePadding: 0,
          clipRule: "nonzero",
          display: "inline",
          overflow: "visible",
          visibility: "visible",
          opacity: 1,
          isolation: "auto",
          mixBlendMode: "normal",
          colorInterpolation: "sRGB",
          colorInterpolationFilters: "linearRGB",
          solidColor: "#000",
          solidOpacity: 1,
          vectorEffect: "none",
          fill: "#ffcf60",
          fillOpacity: 1,
          fillRule: "evenodd",
          stroke: "none",
          strokeWidth: 1,
          strokeLinecap: "round",
          strokeLinejoin: "miter",
          strokeMiterlimit: 4,
          strokeDasharray: "none",
          strokeDashoffset: 0,
          strokeOpacity: 1,
          colorRendering: "auto",
          imageRendering: "auto",
          shapeRendering: "auto",
          textRendering: "auto",
          enableBackground: "accumulate",
        }}
        transform="translate(-29.333 -112.44)"
      />
      <path
        d="M47.928 126.95a5.907 5.907 0 0 0-5.9-5.9 5.905 5.905 0 0 0-5.9 5.9c0 3.252 2.647 5.9 5.9 5.9 3.252 0 5.9-2.648 5.9-5.9z"
        style={{
          color: "#000",
          fontStyle: "normal",
          fontVariant: "normal",
          fontWeight: 400,
          fontStretch: "normal",
          fontSize: "medium",
          lineHeight: "normal",
          fontFamily: "sans-serif",
          fontVariantLigatures: "normal",
          fontVariantPosition: "normal",
          fontVariantCaps: "normal",
          fontVariantNumeric: "normal",
          fontVariantAlternates: "normal",
          fontFeatureSettings: "normal",
          textIndent: 0,
          textAlign: "start",
          textDecoration: "none",
          textDecorationLine: "none",
          textDecorationStyle: "solid",
          textDecorationColor: "#000",
          letterSpacing: "normal",
          wordSpacing: "normal",
          textTransform: "none",
          writingMode: "lr-tb",
          direction: "ltr",
          textOrientation: "mixed",
          dominantBaseline: "auto",
          baselineShift: "baseline",
          textAnchor: "start",
          whiteSpace: "normal",
          shapePadding: 0,
          clipRule: "nonzero",
          display: "inline",
          overflow: "visible",
          visibility: "visible",
          opacity: 1,
          isolation: "auto",
          mixBlendMode: "normal",
          colorInterpolation: "sRGB",
          colorInterpolationFilters: "linearRGB",
          solidColor: "#000",
          solidOpacity: 1,
          vectorEffect: "none",
          fill: "#ffcf60",
          fillOpacity: 1,
          fillRule: "nonzero",
          stroke: "none",
          strokeWidth: 1,
          strokeLinecap: "round",
          strokeLinejoin: "round",
          strokeMiterlimit: 4,
          strokeDasharray: "none",
          strokeDashoffset: 15,
          strokeOpacity: 1,
          colorRendering: "auto",
          imageRendering: "auto",
          shapeRendering: "auto",
          textRendering: "auto",
          enableBackground: "accumulate",
        }}
        transform="translate(-29.333 -112.44)"
      />
      <path
        d="M31.13 126.45a.5.5 0 1 0 0 1h2.474a.5.5 0 1 0 0-1zM50.453 126.45a.5.5 0 1 0 0 1h2.47a.5.5 0 1 0 0-1zM36.06 132.402a.5.5 0 0 0-.343.15l-1.748 1.749a.5.5 0 1 0 .709.707l1.746-1.748a.5.5 0 0 0-.363-.858zM49.723 118.74a.5.5 0 0 0-.344.15l-1.748 1.749a.5.5 0 1 0 .709.707l1.746-1.748a.5.5 0 0 0-.363-.858zM34.318 118.74a.5.5 0 0 0-.35.858l1.749 1.748a.5.5 0 1 0 .707-.707l-1.746-1.748a.5.5 0 0 0-.36-.15z"
        style={{
          color: "#000",
          fontStyle: "normal",
          fontVariant: "normal",
          fontWeight: 400,
          fontStretch: "normal",
          fontSize: "medium",
          lineHeight: "normal",
          fontFamily: "sans-serif",
          fontVariantLigatures: "normal",
          fontVariantPosition: "normal",
          fontVariantCaps: "normal",
          fontVariantNumeric: "normal",
          fontVariantAlternates: "normal",
          fontFeatureSettings: "normal",
          textIndent: 0,
          textAlign: "start",
          textDecoration: "none",
          textDecorationLine: "none",
          textDecorationStyle: "solid",
          textDecorationColor: "#000",
          letterSpacing: "normal",
          wordSpacing: "normal",
          textTransform: "none",
          writingMode: "lr-tb",
          direction: "ltr",
          textOrientation: "mixed",
          dominantBaseline: "auto",
          baselineShift: "baseline",
          textAnchor: "start",
          whiteSpace: "normal",
          shapePadding: 0,
          clipRule: "nonzero",
          display: "inline",
          overflow: "visible",
          visibility: "visible",
          opacity: 1,
          isolation: "auto",
          mixBlendMode: "normal",
          colorInterpolation: "sRGB",
          colorInterpolationFilters: "linearRGB",
          solidColor: "#000",
          solidOpacity: 1,
          vectorEffect: "none",
          fill: "#ffcf60",
          fillOpacity: 1,
          fillRule: "evenodd",
          stroke: "none",
          strokeWidth: 1,
          strokeLinecap: "round",
          strokeLinejoin: "miter",
          strokeMiterlimit: 4,
          strokeDasharray: "none",
          strokeDashoffset: 0,
          strokeOpacity: 1,
          colorRendering: "auto",
          imageRendering: "auto",
          shapeRendering: "auto",
          textRendering: "auto",
          enableBackground: "accumulate",
        }}
        transform="translate(-29.333 -112.44)"
      />
      <path
        d="M155.91 79.008c-3.349.002-6.177 2.268-7.102 5.426-1.037-.877-2.297-1.455-3.67-1.457-3.031 0-5.457 2.366-5.701 5.336-3.301.122-5.95 2.794-5.95 6.125 0 3.409 2.761 6.17 6.17 6.17h22.678c3.41 0 6.17-2.761 6.17-6.17 0-3.148-2.381-5.658-5.426-6.038.167-.622.32-1.252.323-1.898V86.5c0-4.132-3.36-7.492-7.493-7.492z"
        style={{
          color: "#000",
          fontStyle: "normal",
          fontVariant: "normal",
          fontWeight: 400,
          fontStretch: "normal",
          fontSize: "medium",
          lineHeight: "normal",
          fontFamily: "sans-serif",
          fontVariantLigatures: "normal",
          fontVariantPosition: "normal",
          fontVariantCaps: "normal",
          fontVariantNumeric: "normal",
          fontVariantAlternates: "normal",
          fontFeatureSettings: "normal",
          textIndent: 0,
          textAlign: "start",
          textDecoration: "none",
          textDecorationLine: "none",
          textDecorationStyle: "solid",
          textDecorationColor: "#000",
          letterSpacing: "normal",
          wordSpacing: "normal",
          textTransform: "none",
          writingMode: "lr-tb",
          direction: "ltr",
          textOrientation: "mixed",
          dominantBaseline: "auto",
          baselineShift: "baseline",
          textAnchor: "start",
          whiteSpace: "normal",
          shapePadding: 0,
          clipRule: "nonzero",
          display: "inline",
          overflow: "visible",
          visibility: "visible",
          opacity: 1,
          isolation: "auto",
          mixBlendMode: "normal",
          colorInterpolation: "sRGB",
          colorInterpolationFilters: "linearRGB",
          solidColor: "#000",
          solidOpacity: 1,
          vectorEffect: "none",
          fill: "#fff",
          fillOpacity: 1,
          fillRule: "nonzero",
          stroke: "none",
          strokeWidth: 1,
          strokeLinecap: "round",
          strokeLinejoin: "round",
          strokeMiterlimit: 4,
          strokeDasharray: "none",
          strokeDashoffset: 15,
          strokeOpacity: 1,
          colorRendering: "auto",
          imageRendering: "auto",
          shapeRendering: "auto",
          textRendering: "auto",
          enableBackground: "accumulate",
        }}
        transform="translate(-130.854 -63.715)"
      />
    </svg>
  )
  